# Generated by Django 4.0.5 on 2023-01-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('district_name', models.CharField(max_length=100)),
                ('std_code', models.CharField(max_length=25)),
                ('action', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
    ]
