# Generated by Django 3.2.4 on 2023-01-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('statecode', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('statename', models.CharField(max_length=250)),
                ('zonecode', models.IntegerField()),
                ('countrycode', models.IntegerField()),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
