# Generated by Django 4.0.5 on 2022-07-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealerDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('del_name', models.CharField(max_length=200)),
                ('del_add', models.CharField(max_length=1000)),
                ('del_id', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
